import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> initializeTours() async {
  final FirebaseFirestore firestore = FirebaseFirestore.instance;

  final List<Map<String, dynamic>> sampleTours = [
    {
      "title": "Стамбул, Турция",
      "category": "экскурсионный",
      "country": "Турция",
      "city": "Стамбул",
      "imageUrl": "https://example.com/istanbul.jpg",
      "hotel": {
        "name": "Express Inci",
        "stars": 3,
        "meals": "AI - Всё включено",
        "rating": 4.4,
      },
      "flight": {
        "from": "Москва",
        "to": "Стамбул",
        "airline": "Turkish Airlines",
      },
      "basePrice": 62843,
      "pricePerNight": 10000,
      "minNights": 3,
      "maxNights": 14,
      "visaRequired": false,
    },
    {
      "title": "Париж, Франция",
      "category": "романтический",
      "country": "Франция",
      "city": "Париж",
      "imageUrl": "https://example.com/paris.jpg",
      "hotel": {
        "name": "Hotel de Paris",
        "stars": 4,
        "meals": "BB - Завтрак",
        "rating": 4.6,
      },
      "flight": {"from": "Москва", "to": "Париж", "airline": "Air France"},
      "basePrice": 85900,
      "pricePerNight": 13000,
      "minNights": 2,
      "maxNights": 10,
      "visaRequired": true,
    },
    {
      "title": "Бангкок, Таиланд",
      "category": "экзотический",
      "country": "Таиланд",
      "city": "Бангкок",
      "imageUrl": "https://example.com/bangkok.jpg",
      "hotel": {
        "name": "Bangkok Palace",
        "stars": 4,
        "meals": "HB - Полупансион",
        "rating": 4.2,
      },
      "flight": {"from": "Москва", "to": "Бангкок", "airline": "Thai Airways"},
      "basePrice": 74500,
      "pricePerNight": 9000,
      "minNights": 5,
      "maxNights": 14,
      "visaRequired": false,
    },
    {
      "title": "Рим, Италия",
      "category": "исторический",
      "country": "Италия",
      "city": "Рим",
      "imageUrl": "https://example.com/rome.jpg",
      "hotel": {
        "name": "Colosseo Inn",
        "stars": 3,
        "meals": "RO - Без питания",
        "rating": 4.1,
      },
      "flight": {"from": "Москва", "to": "Рим", "airline": "Alitalia"},
      "basePrice": 68800,
      "pricePerNight": 8000,
      "minNights": 3,
      "maxNights": 10,
      "visaRequired": true,
    },
    {
      "title": "Барселона, Испания",
      "category": "пляжный",
      "country": "Испания",
      "city": "Барселона",
      "imageUrl": "https://example.com/barcelona.jpg",
      "hotel": {
        "name": "Barcelona Beach Hotel",
        "stars": 4,
        "meals": "AI - Всё включено",
        "rating": 4.5,
      },
      "flight": {"from": "Москва", "to": "Барселона", "airline": "Vueling"},
      "basePrice": 79500,
      "pricePerNight": 11000,
      "minNights": 4,
      "maxNights": 12,
      "visaRequired": true,
    },
    {
      "title": "Прага, Чехия",
      "category": "экскурсионный",
      "country": "Чехия",
      "city": "Прага",
      "imageUrl": "https://example.com/prague.jpg",
      "hotel": {
        "name": "Prague Central",
        "stars": 3,
        "meals": "BB - Завтрак",
        "rating": 4.3,
      },
      "flight": {"from": "Москва", "to": "Прага", "airline": "Czech Airlines"},
      "basePrice": 62000,
      "pricePerNight": 8500,
      "minNights": 3,
      "maxNights": 10,
      "visaRequired": true,
    },
    {
      "title": "Дубай, ОАЭ",
      "category": "шоппинг",
      "country": "ОАЭ",
      "city": "Дубай",
      "imageUrl": "https://example.com/dubai.jpg",
      "hotel": {
        "name": "Dubai Marina Hotel",
        "stars": 5,
        "meals": "AI - Всё включено",
        "rating": 4.7,
      },
      "flight": {"from": "Москва", "to": "Дубай", "airline": "Emirates"},
      "basePrice": 94500,
      "pricePerNight": 15000,
      "minNights": 3,
      "maxNights": 10,
      "visaRequired": false,
    },
    {
      "title": "Каир, Египет",
      "category": "экзотический",
      "country": "Египет",
      "city": "Каир",
      "imageUrl": "https://example.com/cairo.jpg",
      "hotel": {
        "name": "Nile View",
        "stars": 4,
        "meals": "FB - Полный пансион",
        "rating": 4.0,
      },
      "flight": {"from": "Москва", "to": "Каир", "airline": "EgyptAir"},
      "basePrice": 58000,
      "pricePerNight": 7000,
      "minNights": 4,
      "maxNights": 10,
      "visaRequired": false,
    },
    {
      "title": "Афины, Греция",
      "category": "исторический",
      "country": "Греция",
      "city": "Афины",
      "imageUrl": "https://example.com/athens.jpg",
      "hotel": {
        "name": "Acropolis View",
        "stars": 3,
        "meals": "HB - Полупансион",
        "rating": 4.2,
      },
      "flight": {"from": "Москва", "to": "Афины", "airline": "Aegean Airlines"},
      "basePrice": 64000,
      "pricePerNight": 9000,
      "minNights": 3,
      "maxNights": 12,
      "visaRequired": true,
    },
    {
      "title": "Токио, Япония",
      "category": "технологии",
      "country": "Япония",
      "city": "Токио",
      "imageUrl": "https://example.com/tokyo.jpg",
      "hotel": {
        "name": "Tokyo City Hotel",
        "stars": 4,
        "meals": "BB - Завтрак",
        "rating": 4.8,
      },
      "flight": {"from": "Москва", "to": "Токио", "airline": "Japan Airlines"},
      "basePrice": 112000,
      "pricePerNight": 18000,
      "minNights": 5,
      "maxNights": 14,
      "visaRequired": true,
    },
  ];

  for (final tour in sampleTours) {
    final query =
        await firestore
            .collection('tours')
            .where('title', isEqualTo: tour['title'])
            .get();
    if (query.docs.isEmpty) {
      await firestore.collection('tours').add(tour);
    }
  }
}
